version: "3.9"
services:
  api:
    build:
      context: .
    image: bosagora/boa-space-backend:dev
    ports:
      - "4000:4000"
    volumes:
      - $HOME/.aws/credentials:/.aws/credentials:ro
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    depends_on:
      - db
  db:
    image: postgres:15.1
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
