# Warning: This workflow is intended for testnet deployment only
# Use this always before deploying to the Production environment
name: TEST deploy of chosen release tagged Docker Image
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name (e.g. v1.0.0)'
        required: true
jobs:
  run-playbook:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEVNET_PEM }}
          name: id_rsa # optional
          known_hosts: |
            52.220.66.34 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBAJBOLXo9mH0TZDcW5w2XNTT5VseWzzTPZU6KtaBb6ThWS+MNpQUJTwF/TD2ZmnJJHQ4lnX7PeDgCXKqKexjLBw=
      - name: run playbook
        run: |
          ansible-playbook -u ubuntu \
          --extra-vars "TAG=${{ github.event.inputs.tag }}" \
          --extra-vars "RPC_URL=https://testnet.bosagora.org" \
          --extra-vars "NODE_DEV=false" \
          --extra-vars "DEPLOY_TARGET=TEST" \
          --extra-vars "JWT_SECRET=${{ secrets.JWT_SECRET_TEST }}" \
          --extra-vars "AWS_ACCESS_KEY_ID=${{ secrets.IAM_TEST_AWS_ACCESS_KEY_ID }}" \
          --extra-vars "AWS_SECRET_ACCESS_KEY=${{ secrets.IAM_TEST_AWS_SECRET_ACCESS_KEY }}" \
          --extra-vars "BUCKET_NAME=test.boaspace.io" \
          --extra-vars "POSTGRES_HOST=boa-space-test.cpx85wvt8szu.ap-southeast-1.rds.amazonaws.com" \
          --extra-vars "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD_TEST }}" \
          --extra-vars "SHAREDASSET_CONTRACT=0x2fddd0f488B767E8Dd42aE4E60f0685A2e15b1Fd" \
          --extra-vars "LAZY_MINT_ADAPTER=0x790c4c73155F89F93ad18e3b3B483B688E867c4b" \
          --extra-vars "NATIVE_TOKEN=0x0000000000000000000000000000000000000000" \
          -i ansible/inventory_test.yml ansible/deploy.yml
