# This workflow will automatically build a new docker image for the new release tag and push it to docker hub.
name: Auto Build and publish release image
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  main:
    if: github.repository == 'bosagora/boa-space-backend'
    runs-on: ubuntu-latest
    env:
      HAVE_DOCKERHUB_SECRET: ${{ secrets.DHUB_TOKEN != '' && secrets.DHUB_USER != '' }}
    steps:
      - name: Get version number
        shell: bash
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        id: login
        if: env.HAVE_DOCKERHUB_SECRET
        with:
          username: ${{ secrets.DHUB_USER }}
          password: ${{ secrets.DHUB_TOKEN }}
      - name: 'Build and push'
        uses: docker/build-push-action@v3
        with:
          # Either 'success' or 'skipped'
          push: ${{ steps.login.outcome == 'success' }}
          tags: bosagora/boa-space-backend:${{ steps.version.outputs.VERSION }}
